services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
  samizdat:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
    image: samizdat
    ports:
      - "80:3000"
